SET client_encoding = 'UTF8';
SET timezone = 'UTC';

CREATE TABLE schema_meta (
  version BIGINT NOT NULL,
  applied_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE source_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  kind TEXT NOT NULL CHECK (kind IN ('jitendex', 'kaishi')),
  version TEXT NOT NULL,
  url TEXT NOT NULL,
  sha256 TEXT NOT NULL,
  local_path TEXT NOT NULL,
  extractor_version TEXT NOT NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE kaishi_note (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  snapshot_id BIGINT NOT NULL,
  note_id BIGINT NOT NULL,
  word TEXT NOT NULL,
  reading TEXT NOT NULL,
  meaning_en TEXT NOT NULL,
  sentence_ja TEXT NOT NULL,
  sentence_en TEXT NOT NULL,
  source_sha256 TEXT NOT NULL
);

CREATE TABLE article (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  snapshot_id BIGINT NOT NULL,
  bank_number BIGINT NOT NULL,
  entry_ordinal BIGINT NOT NULL,
  expression TEXT NOT NULL,
  reading TEXT NOT NULL,
  sequence BIGINT NOT NULL,
  raw_json TEXT NOT NULL,
  source_sha256 TEXT NOT NULL,
  structural_fingerprint TEXT,
  selected BIGINT NOT NULL DEFAULT 0 CHECK (selected IN (0, 1))
);

CREATE TABLE selection_candidate (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  note_id BIGINT NOT NULL,
  article_id BIGINT NOT NULL,
  sequence BIGINT NOT NULL,
  match_kind TEXT NOT NULL,
  evidence_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE selection_decision (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  note_id BIGINT NOT NULL,
  sequence BIGINT,
  decision TEXT NOT NULL CHECK (decision IN ('included', 'excluded', 'unresolved')),
  actor TEXT NOT NULL,
  reason TEXT NOT NULL,
  review_status TEXT NOT NULL CHECK (review_status IN ('pending', 'accepted', 'rejected')),
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  jitendex_snapshot_id BIGINT NOT NULL,
  kaishi_snapshot_id BIGINT NOT NULL,
  selection_sha256 TEXT NOT NULL,
  extractor_version TEXT NOT NULL,
  prompt_sha256 TEXT NOT NULL,
  review_prompt_sha256 TEXT NOT NULL,
  terminology_sha256 TEXT NOT NULL,
  limits_json TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text),
  pipeline_version TEXT NOT NULL DEFAULT 'scalar-v1'
);

CREATE TABLE translation_unit (
  id TEXT NOT NULL,
  run_id BIGINT NOT NULL,
  article_id BIGINT NOT NULL,
  json_pointer TEXT NOT NULL,
  role TEXT NOT NULL,
  source_text TEXT NOT NULL,
  source_sha256 TEXT NOT NULL,
  protected_tokens_json TEXT NOT NULL DEFAULT '[]',
  byte_count BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ready'
);

CREATE TABLE batch (
  id TEXT NOT NULL,
  run_id BIGINT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'translation',
  manifest_sha256 TEXT NOT NULL,
  serialized_bytes BIGINT NOT NULL,
  article_count BIGINT NOT NULL,
  unit_count BIGINT NOT NULL,
  state TEXT NOT NULL DEFAULT 'ready',
  lease_token TEXT,
  lease_expires_at TEXT,
  attempt_count BIGINT NOT NULL DEFAULT 0,
  manifest_path TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE batch_item (
  batch_id TEXT NOT NULL,
  unit_id TEXT NOT NULL,
  ordinal BIGINT NOT NULL
);

CREATE TABLE attempt (
  id TEXT NOT NULL,
  batch_id TEXT NOT NULL,
  worker_id TEXT NOT NULL,
  model TEXT NOT NULL,
  prompt_sha256 TEXT NOT NULL,
  lease_token TEXT,
  request_path TEXT NOT NULL,
  response_path TEXT,
  outcome TEXT NOT NULL DEFAULT 'claimed',
  error_json TEXT,
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text),
  completed_at TEXT,
  effective_model_id TEXT,
  reasoning_effort TEXT,
  transport TEXT CHECK (transport IS NULL OR transport IN ('responses-sync', 'batch-api', 'codex-agent')),
  api_request_id TEXT,
  api_custom_id TEXT,
  api_job_id TEXT,
  input_tokens BIGINT CHECK (input_tokens IS NULL OR input_tokens >= 0),
  cached_input_tokens BIGINT CHECK (cached_input_tokens IS NULL OR cached_input_tokens >= 0),
  output_tokens BIGINT CHECK (output_tokens IS NULL OR output_tokens >= 0),
  total_tokens BIGINT CHECK (total_tokens IS NULL OR total_tokens >= 0),
  finish_reason TEXT,
  status_reason TEXT,
  latency_ms BIGINT CHECK (latency_ms IS NULL OR latency_ms >= 0)
);

CREATE TABLE translation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  run_id BIGINT NOT NULL,
  unit_id TEXT NOT NULL,
  attempt_id TEXT NOT NULL,
  target_text TEXT NOT NULL,
  confidence TEXT NOT NULL,
  review_reason TEXT,
  target_sha256 TEXT NOT NULL,
  accepted BIGINT NOT NULL DEFAULT 0 CHECK (accepted IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE review (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  translation_id BIGINT NOT NULL,
  attempt_id TEXT,
  decision TEXT NOT NULL CHECK (decision IN ('accept', 'replace', 'needs_adjudication')),
  replacement_target TEXT,
  reason TEXT,
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE validation_issue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  run_id BIGINT,
  unit_id TEXT,
  attempt_id TEXT,
  validator TEXT NOT NULL,
  severity TEXT NOT NULL,
  code TEXT NOT NULL,
  details_json TEXT NOT NULL,
  resolved_at TEXT,
  waiver_reason TEXT,
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE audit_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  event_type TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  details_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE export (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  run_id BIGINT NOT NULL,
  output_path TEXT NOT NULL,
  manifest_sha256 TEXT NOT NULL,
  zip_sha256 TEXT NOT NULL,
  verified BIGINT NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE export_file (
  export_id BIGINT NOT NULL,
  path TEXT NOT NULL,
  sha256 TEXT NOT NULL,
  byte_count BIGINT NOT NULL
);

CREATE TABLE run_article (
  run_id BIGINT NOT NULL,
  article_id BIGINT NOT NULL,
  structural_fingerprint TEXT NOT NULL
);

CREATE TABLE attempt_cost_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  attempt_id TEXT NOT NULL,
  price_snapshot_date TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD',
  input_price_per_million TEXT NOT NULL,
  cached_input_price_per_million TEXT NOT NULL,
  output_price_per_million TEXT NOT NULL,
  price_multiplier TEXT NOT NULL DEFAULT '1',
  input_tokens BIGINT NOT NULL,
  cached_input_tokens BIGINT NOT NULL,
  output_tokens BIGINT NOT NULL,
  computed_cost TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);

CREATE TABLE jitendex_tag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  snapshot_id BIGINT NOT NULL,
  source_kind TEXT NOT NULL CHECK (source_kind IN ('embedded_tooltip', 'tag_bank')),
  source_key TEXT NOT NULL,
  code TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL,
  label_en TEXT NOT NULL,
  description_en TEXT NOT NULL,
  source_sha256 TEXT NOT NULL,
  occurrence_count BIGINT NOT NULL CHECK (occurrence_count >= 0),
  source_metadata_json TEXT NOT NULL DEFAULT '{}',
  label_ru TEXT,
  description_ru TEXT,
  confidence TEXT CHECK (confidence IS NULL OR confidence IN ('high', 'medium', 'low')),
  review_reason TEXT,
  translation_model TEXT,
  reasoning_effort TEXT,
  prompt_sha256 TEXT,
  translated_at TEXT,
  translation_source TEXT,
  translation_source_sha256 TEXT,
  translation_source_path TEXT,
  approved_at TEXT
);

CREATE TABLE jitendex_tag_translation_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tag_id BIGINT NOT NULL,
  label_ru TEXT,
  description_ru TEXT,
  confidence TEXT,
  review_reason TEXT,
  translation_model TEXT,
  reasoning_effort TEXT,
  prompt_sha256 TEXT,
  translation_source TEXT,
  translation_source_sha256 TEXT,
  translation_source_path TEXT,
  translated_at TEXT,
  archived_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text),
  replacement_source_sha256 TEXT NOT NULL
);

CREATE TABLE frequency_source (
  source TEXT NOT NULL,
  source_sha256 TEXT NOT NULL,
  rank_limit BIGINT NOT NULL CHECK (rank_limit > 0),
  local_path TEXT NOT NULL,
  title TEXT,
  revision TEXT,
  parser_version TEXT NOT NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE frequency_term (
  source TEXT NOT NULL,
  source_sha256 TEXT NOT NULL,
  rank BIGINT NOT NULL,
  term TEXT NOT NULL,
  matched BIGINT NOT NULL DEFAULT 0 CHECK (matched IN (0, 1))
);

CREATE TABLE frequency_article (
  source TEXT NOT NULL,
  source_sha256 TEXT NOT NULL,
  rank BIGINT NOT NULL,
  term TEXT NOT NULL,
  article_id BIGINT NOT NULL,
  match_kind TEXT NOT NULL CHECK (match_kind IN ('expression', 'reading'))
);

CREATE TABLE translation_canonicalization_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  run_id BIGINT NOT NULL,
  unit_id TEXT NOT NULL,
  translation_id BIGINT NOT NULL,
  previous_target_text TEXT NOT NULL,
  previous_target_sha256 TEXT NOT NULL,
  canonical_target_text TEXT NOT NULL,
  canonical_target_sha256 TEXT NOT NULL,
  mapping_source TEXT NOT NULL,
  mapping_identity_json TEXT NOT NULL,
  canonicalizer_version TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC')::text)
);
